version: '3'
services:
  php_apache:
    container_name: apache_php_banpdm
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9481:80
    volumes:
      - ./www:/var/www/html
    networks:
      - banpdm_network
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8.1.0
    container_name: mysql_banpdm
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: animasiku_studio
    # MYSQL_USER: root
    ports:
      - 9482:3306
    volumes:
      - volume-db:/var/lib/mysql
    restart: always
    # command: --sql-mode="NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    networks:
      - banpdm_network

  redis:
    image: redis:7.2.1
    container_name: redis_banpdm
    restart: always
    ports:
      - 9483:6379
    networks:
      - banpdm_network

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin_banpdm
    restart: always
    ports:
      - 9484:80
    environment:
      - PMA_ARBITRARY:1
      - PMA_HOST:mysql
      - UPLOAD_LIMIT=750M
      - MEMORY_LIMIT=750M
      - MAX_EXECUTION_TIME=300
      - MYSQL_USERNAME:root
      - MYSQL_ROOT_PASSWORD:password
    depends_on:
      - db
    networks:
      - banpdm_network

networks:
  banpdm_network:


volumes:
  volume-db:
