version: '3'
services:
    php_apache:
      container_name: apache_php_banpdm
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8481:80
      volumes:
        - ./www:/var/www/html
      networks:
        - banpdm_network
      depends_on:
        - db

    db:
      image: mysql:8.1.0
      container_name: mysql_banpdm
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: company
        # MYSQL_USER: root
      ports:
        - 8482:3306
      volumes:
        - ./mysql:/var/lib/mysql
      restart: always
      networks:
        - banpdm_network

    redis:
      image: redis:7.2.1
      container_name: redis_banpdm
      restart: always
      ports:
        - 8483:6379
      networks:
        - banpdm_network 

    phpmyadmin:
      image: phpmyadmin:5.2.1
      container_name: phpmyadmin_banpdm
      restart: always
      ports:
        - 8484:80
      environment:
        - PMA_ARBITRARY:1
        - PMA_HOST:mysql
        - MYSQL_USERNAME:root
        - MYSQL_ROOT_PASSWORD:password
      depends_on:
        - db
      networks:
        - banpdm_network     

networks:
  banpdm_network:
